export default {
  movies: [
    {
      title: "The Shawshank Redemption",
      rank: "1",
      id: "tt0111161",
      watched: false,
    },
    {
      title: "The Godfather",
      rank: "2",
      id: "tt0068646",
      watched: false,
    },
    {
      title: "The Godfather: Part II",
      rank: "3",
      id: "tt0071562",
      watched: false,
    },
    {
      title: "Pulp Fiction",
      rank: "4",
      id: "tt0110912",
      watched: false,
    },
    {
      title: "The Good, the Bad and the Ugly",
      rank: "5",
      id: "tt0060196",
      watched: false,
    },
    {
      title: "The Dark Knight",
      rank: "6",
      id: "tt0468569",
      watched: false,
    },
    {
      title: "12 Angry Men",
      rank: "7",
      id: "tt0050083",
      watched: false,
    },
    {
      title: "Schindler's List",
      rank: "8",
      id: "tt0108052",
      watched: false,
    },
    {
      title: "The Lord of the Rings: The Return of the King",
      rank: "9",
      id: "tt0167260",
      watched: false,
    },
    {
      title: "Fight Club",
      rank: "10",
      id: "tt0137523",
      watched: false,
    },
    {
      title: "Star Wars: Episode V - The Empire Strikes Back",
      rank: "11",
      id: "tt0080684",
      watched: false,
    },
    {
      title: "The Lord of the Rings: The Fellowship of the Ring",
      rank: "12",
      id: "tt0120737",
      watched: false,
    },
    {
      title: "One Flew Over the Cuckoo's Nest",
      rank: "13",
      id: "tt0073486",
      watched: false,
    },
    {
      title: "Inception",
      rank: "14",
      id: "tt1375666",
      watched: false,
    },
    {
      title: "Goodfellas",
      rank: "15",
      id: "tt0099685",
      watched: false,
    },
    {
      title: "Star Wars",
      rank: "16",
      id: "tt0076759",
      watched: false,
    },
    {
      title: "Seven Samurai",
      rank: "17",
      id: "tt0047478",
      watched: false,
    },
    {
      title: "Forrest Gump",
      rank: "18",
      id: "tt0109830",
      watched: false,
    },
    {
      title: "The Matrix",
      rank: "19",
      id: "tt0133093",
      watched: false,
    },
    {
      title: "The Lord of the Rings: The Two Towers",
      rank: "20",
      id: "tt0167261",
      watched: false,
    },
    {
      title: "City of God",
      rank: "21",
      id: "tt0317248",
      watched: false,
    },
    {
      title: "Se7en",
      rank: "22",
      id: "tt0114369",
      watched: false,
    },
    {
      title: "The Silence of the Lambs",
      rank: "23",
      id: "tt0102926",
      watched: false,
    },
    {
      title: "Once Upon a Time in the West",
      rank: "24",
      id: "tt0064116",
      watched: false,
    },
    {
      title: "Casablanca",
      rank: "25",
      id: "tt0034583",
      watched: false,
    },
    {
      title: "The Usual Suspects",
      rank: "26",
      id: "tt0114814",
      watched: false,
    },
    {
      title: "Raiders of the Lost Ark",
      rank: "27",
      id: "tt0082971",
      watched: false,
    },
    {
      title: "Rear Window",
      rank: "28",
      id: "tt0047396",
      watched: false,
    },
    {
      title: "It's a Wonderful Life",
      rank: "29",
      id: "tt0038650",
      watched: false,
    },
    {
      title: "Psycho",
      rank: "30",
      id: "tt0054215",
      watched: false,
    },
  ],
};
